### ISSUE TITLE
onelogin.com blocked

### ISSUE THREAD

**Issue by originate-hosting** [EFForg/privacybadgerchrome#317]
onelogin.com is a Shared Sign On (SSO) service.  It should never be blocked, as that interferes with authentication.

**Comment by cooperq** [comment]
@originate-hosting I could add onelogin.com to the cookieblock list, but I don't think that would solve your problem, since you probably need cookies to authenticate the user. However, there is something you can do to make sure that privacy badger does not block your service. You can adopt EFF's new preliminary Do Not Track policy which is posted here: https://www.eff.org/files/dnt-policy-preliminary.txt This is a precursor to the more stringent Do Not Track policy which we are working on here: https://www.eff.org/dnt-policy
By adopting this policy you will guarantee that privacy badger does not block your service. You are also welcome to help us reach a final draft of the real DNT policy by submitting your suggestions for it. Thank you!

**Comment by cooperq** [comment]
Or if you are not the administrator for onelogin.com and just a user you can move it's slider to green to unblock it in privacy badger's settings.

**Comment by ghostwords** [comment]
Seems related to #1175.
