### ISSUE TITLE
Disqus comment destroyed upon login/PB enable

### ISSUE THREAD

**Issue by Sequoia** [EFForg/privacybadgerchrome#322]
# Reproduction
1. Fresh PB install, running long enough to start blocking disqus
2. Navigate to site using disqus 3rd party scripts & scroll/click to load comments
3. Click reply after a comment
4. Enter comment into box
5. "Post as:" disqus account (click disqus logo button)
6. In popup, provide disqus creds & submit
7. When presented with PB overlay, choose "always allow"

## Expected
Comment is posted as written (default/normal disqus behavior)

## Actual
Page is reloaded & comment is destroyed

**Comment by Sequoia** [comment]
stopgap for this could be to just copy the user's comment & print it to overlay w/warning that they need to c/p it or it will be lost.

**Comment by cooperq** [comment]
Thanks for the bug report sequoia, I will think about how best to fix this. The page has to be reloaded so there is no way around that. But maybe your stopgap would work.

**Comment by SwartzCr** [comment]
Is this something that could be fixed by adding disqus to the default greylist

**Comment by cooperq** [comment]
So the thing is, I think that this will probably only happen once. I'm assuming that most users will click 'always allow' and will therefore not run into this problem again.  Since this is the only case where this happens I am wary about adding a bunch of extra code just as a workaround for Disqus that the user will probably only have to deal with once.
