### ISSUE TITLE
Chrome high cpu usage with numerous tabs open

### ISSUE THREAD

**Issue by cypherpunk** [EFForg/privacybadgerchrome#324]
I find my PC grinding to a halt with 100% CPU usage when I have several Chrome tabs open and those tabs have been running a while.  The longer multiple tabs are open the more bogged down the machine gets, especially during audio playback (VLC player).  This is on a Win7-64 machine with 2.5-GHz Core i5 and 16GB RAM.  If I wait 2-3 minutes, the machine comes back to life and runs normally for 10-15 minutes most of the time before slowing again.

I noticed the Chrome status bar displaying a message about waiting for "extension Privacy Badger" on multiple occasions while my machine was bogged down.  I disabled the extension and things have been running fine for the past hour.  I had the current version installed in Chrome.

**Comment by cooperq** [comment]
What a bummer! I will look into this. Thank you.

**Comment by SwartzCr** [comment]
Any updates? Have you still been running into this issue?

**Comment by gpaezpaquetexpresscommx** [comment]
Seeing high cpu usage in Chrome Canary, OSX El Capitan

**Comment by Ikijibiki** [comment]
Am having the same issue with the latest Chrome 32-bit on Windows 10 Pro. Disable Badger and everything is fine.

**Comment by kstenerud** [comment]
Same here. Massive CPU usage, even getting Chrome stuck completely in OSX El Capitain. Since this won't be fixed I'll just remove privacy badger.

**Comment by cooperq** [comment]
I suspect that this bug is related to how the ABP subsystem handles data. I think that completion of #762 (which is my top priority currently) will fix this issue.

**Comment by slick9115** [comment]
I had this happen today and can add my scenario:

1. Sites will stop responding. I can't even get the local Chrome splash page with 8-history tiles and a bigger search bar (Chrome 49.0.2623.87 (64-bit) // PB  2016.3.2).

2. OSX Activity Monitor will show high utilizations for "Google Chrome Helper."

3. All other browsers/net services on my computer will work.

4. Disabling PB will immediately release resources, and the web is accessible again.

I haven't done much other troubleshooting because I have work to do, but I can provide logs if necessary. The internet is noticeably faster now too... which makes me think this extension needs a performance boost... or code review.

-Slick

**Comment by hachi** [comment]
This happens probably once a week for me. Is there a way to request a stack trace of the PB code when it occurs? I usually go to the task manager and kill the process PB is running under and then click the "PB has crashed" bubble to start it back up.

**Comment by cooperq** [comment]
Is this still an issue with the latest version, 2016.4.13 ?

**Comment by srikanthnv** [comment]
Not the OP, but this is still an issue for me with the latest version of PB and chrome on OSX. This might be a red herring but there seems to be some correlation with opening multiple tabs at once.

**Comment by drewbrew** [comment]
I ran into it this morning trying to get to http://gameofthrones.wikia.com/wiki/Oberyn_Martell on El Capitan on a mid-2014 MacBook Pro (8 GB RAM) on Chrome stable and 48 tabs open.

I also have [uBlock 0.8.7.0](https://github.com/chrisaljoudi/uBlock) installed, FWIW.

**Comment by zeeZ** [comment]
2016.4.13 (with uBlock Origin 1.6.8 FWIW) and Chrome version 49.0.2623.112 m. Maxes out a CPU core and blocks any new requests unless restarted.

**Comment by hachi** [comment]
Just happened in chrome 50 with 25 tabs open, version 2016.4.13 on OSX

**Comment by chrisamiller** [comment]
Yes, I see this issue probably twice a week and can confirm that it persists on version 2016.4.13 (chrome v 50.0.2661.86).

**Comment by cooperq** [comment]
Okay, This should be completely fixed in the latest version of privacy badger. As of today I have only deployed it to 10% of users (it has some huge changes!) but if you want to try it out early you can take the following steps. 
1. Download the crx file [from the chrome web store] (https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1rX98iOE5SwxVXgdVTMTKqobiCFyOuS_jNFoVMdRhW-bEA7QhvVJw2hrKrZS8b8ThMYsv0t-wxxLr4D-Sm2ZC1AMZSmuW2zjq5MsW529CVI2Rtq2QO7xWEQg/pkehgijcmpdhfbdbbnkijodmdjhbjlgp_main.crx)
2. Open a new tab to [chrome://extensions](chrome://extensions)
3. Drag the downloaded file and drop it onto the extensions window. 
You should now have Privacy Badger version 2016.5.15
If this doesn't fix the problem please let me know. If you find any new bugs please file a separate issue.

**Comment by slick9115** [comment]
I have yet to see this happen lately. I would close this out.
