### ISSUE TITLE
Supercookie detection 

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#362]
Privacy badger should detect common forms of super cookies and add sites setting them to it's heuristic.

**Comment by cooperq** [comment]
@gunesacar is working on this for local storage, but he may have some problems. @gunesacar can you give some detail as to where you are at with this?

**Comment by gunesacar** [comment]
I looked into the detection of local storage based supercookies and ran into the following difficulties.

* Chrome's extension API doesn't support accessing or manipulating local storage at the moment (see [Chromium bug #78093](https://code.google.com/p/chromium/issues/detail?id=78093)). So  I've tried following two ways to get a hold of local storage:

* I tried to override `Storage.prototype.get/setItem` to capture access to local storage (similar to this [SO answer](http://stackoverflow.com/questions/2010892/storing-objects-in-html5-localstorage/5790739#5790739)). Although this has worked for scripts using `localStorage.get/setItem` methods, I wasn't able to capture calls using dot(`localStorage.item`) or array notation (`localStorage["item"]`). If I could, next step would be to find the domain of the script accessing the local storage (should be feasible using V8 Stack Trace API as Alexei does in Chameleon.)

* As an alternative I tried to iterate over the items already in the local storage instead of capturing function calls/property accesses. Using a content script I was able to get all the items in the local storage for a given frame. But then I couldn't find a way to get the domain of the script which set the item.

I checked some Chrome extensions allowing people to discover the content of their local storage. It turned that none of them could report the origin of the items (e.g. [html5-localstorage-manager](https://github.com/AndreLion/html5-localstorage-manager)
[LocalStorage Monitor](https://chrome.google.com/webstore/detail/localstorage-monitor/bpidlidmmmnapeldonddkjmmjkpeiabi?hl=en)
)

As a summary, I couldn't find a way to get enough info about local storage to build the detection on top of this. Any help or tip is more than welcome!

**Comment by michael-oneill** [comment]
Can you inject script into the non-consensual third-party trackers document origin? The injected script then can call localStorage.clear().

**Comment by gunesacar** [comment]
Thanks for the tip but I'm not really sure. Maybe someone with more knowledge about Chrome extensions may reply.
Here's what I know:
* We can inject scripts into frames using content scripts, but not to particular document origins (or execution/security contexts). (The content scripts still runs in a different execution environment but I believe you can circumvent this.)
* Theoretically you could modify response bodies on the fly and inject to all incoming scripts. Apart from it sounds very dirty, I'm not sure if it's possible given [this open issue](https://code.google.com/p/chromium/issues/detail?id=104058).
* The closest thing I've found was [chrome.devtools.inspectedWindow.eval](https://developer.chrome.com/extensions/devtools_inspectedWindow#method-eval) which has a `contextSecurityOrigin` argument. You could pass the execution context you want to run your script in. But you need to be inspecting a page to use this function.
* I asked a question on [Chromium-extensions mailing list](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/ipjex0gLBF0), but didn't get any reply back.

**Comment by michael-oneill** [comment]
If a content script will execute in all 3rd party iframes then you can communicate to it using postMessage. Send a message like "remove localStorage" to non-good guys from the top level context.
It begs the question about how to handle Content-Security-Policy headers from the third-parties, but that may be handle-able before it becomes a problem.

**Comment by gunesacar** [comment]
Yes but I think many of the 3rd party scripts will not run on their own frames. When a page includes a 3rd party script from tracker.com (with a `<script src=...>` tag), the tracker script will run on the same frame as the top-level domain's scripts (and other 3rd party scripts included by the page.)

Then we won't be able to distinguish local storage items of top-level domain from those of 3rd party scripts.

But this may work for the cases where the tracker script is included as an iFrame (like Facebook social widgets etc.)

**Comment by cooperq** [comment]
You can get access to the browser document object from a content script by injecting a script tag into the page. I did this for cookieblocking, and @ghostwords did it and added message passing back to the content script (which can then pass messages back to the addon.) 
You are correct that you can't inject scripts into particular document origins but you could inject it into all frames and then have it ask the add-on if it should run in this particular document origin or not. I'm not sure that solves your problem of not being able to listen for localstorage changes though.

**Comment by gunesacar** [comment]
Let me give a try to this idea in the weekend. But I suspect the content script will only be able to run in the frame's (or page's) context  - but not in the context of different scripts included by the frame.

**Comment by ghostwords** [comment]
> I wasn't able to capture calls using dot(localStorage.item) or array notation (localStorage["item"])

I think the core problem here is that it's not clear how to hook into *all* property accesses on an object, without first knowing the names of those properties. We should be able to do this with the [Proxy API](http://soft.vub.ac.be/~tvcutsem/proxies/), but unfortunately, it's [not yet available in Chrome](https://code.google.com/p/v8/issues/detail?id=1543). A version of it should already be in Firefox.

We (mostly) know how to figure out initiating/originating scripts (via stack traces), and we know how to work around content script sandboxes with dynamic script injection + custom events for communication.

**Comment by ghostwords** [comment]
> I suspect the content script will only be able to run in the frame's (or page's) context - but not in the context of different scripts included by the frame.

Take a look at [this content script](https://github.com/EFForg/privacybadgerchrome/blob/fabc7ae1ed659b7b2250966c6ef5c87c6e574a96/src/fingerprinting.js#L265-L277) for the workaround. Original version [here](https://github.com/ghostwords/chameleon/blob/master/src/js/inject.js).

**Comment by ghostwords** [comment]
Ah, sorry, I see you mean something else. We'd need to be able to modify response bodies for that, right? ... but we can't even see them yet (with webRequest anyway).

**Comment by pde** [comment]
@gunesacar I think we should begin by handling the case where the local storage is associated with a 3rd party origin.  If there's a <tt><script src="blah"</tt> include into the top level DOM, that's a different case, and it isn't necessarily cross-domain tracking (but see #367).

So I think our plan should be: inject content script, see if we're a third party and there is anything in localStorage, if yes then return true in <tt>hasSuperCookieTracking()</tt>, or if that's impossible because of execution context, do something else that has the same consequences.

**Comment by pde** [comment]
@michael-oneill if we see this type of behaviour from a third party script, we probably want to block that domain entirely (privacy badger menu state red), not just block the supercookies (which would be analagous to privacy badger menu state yellow).

**Comment by gunesacar** [comment]
Thanks for all the help and feedback! Here's a first stab: https://github.com/EFForg/privacybadgerchrome/compare/master...gunesacar:super_cookie_detection

* We have a new content script (`supercookie.js`). It injects a page script, which then checks potential supercookies in the local storage.
* I followed @ghostwords's `fingerprinting.js` example for content script injection.
* Feedback about my silly [entropy estimation function](https://github.com/gunesacar/privacybadgerchrome/commit/ed68b7a3a74d211d488778144e6cf190c738e5d7#diff-39ec0f796435c979498d5ede98504c1bR53) is more than welcome. Here's a [fiddle](https://jsfiddle.net/6xqt8r39/) for fiddling with it.
* The main problem with the current version is that `hasSupercookieTracking` function is called before we hear from the supercookie check. Maybe we should (persistently) store the supercookie detection result (`recordPrevalence`?) instead of just adding it to tabData. (See, TODO's in the code and logs on the background page, e.g. how `Detected high-entropy local storage...` immediately follows `No SupercookieTracking...` for the same tab and frameId)
* Also, note that it's not possible to make sync. calls to injected script (e.g. calling local storage check from `hasSupercookieTracking`).
* Excuse my initial confusion: all the local storage items added by a 3rd-party script embedded in a frame (or page) will have that frame's origin (not the script's origin!). So, we are able to detect supercookies set in the context of a third-party frame (without being able to distinguish the script's origin, which is irrelevant).
* Demo pages for testing: 
  * [local storage set by a 1st-party (inline) script](https://securehomes.esat.kuleuven.be/~gacar/dev/test/localstorage/setlocalstorage.html)
  * [local storage set by a 3rd-party script](https://securehomes.esat.kuleuven.be/~gacar/dev/test/localstorage/third_party_ls.html)
  * [local storage set by a 3rd-party frame](https://securehomes.esat.kuleuven.be/~gacar/dev/test/localstorage/setlocalstorage_byexternal_frame.html)

As always, feedback is more than welcome, especially with the problem with the timing.

**Comment by gunesacar** [comment]
In case it helps with thinking about entropy estimation and supercookie detection, here's the list of local storage items stored on Alexa top 100K sites:
https://securehomes.esat.kuleuven.be/~gacar/dev/pb/20141127-192933_FL0_CO0_1_100000-report.html

**Comment by cooperq** [comment]
Thanks gunes this is great stuff! I feel a bit like the entropy estimation stuff should go in the addon instead of the content script, that way we can reuse it for other things (like cookies and other supercookies). Similarly I would but all of the checking whether this is a third party and whether privacy badger is enabled in the addon code. The content script can just send a domain name and the contents of local storage to the addon and let the addon do the heavy lifting. 

As for the timing issue I think storing and then reading out of a a presistent data structure like
`supercookie_domains = { domain1.com: true, domain2.com: true, ...} `
is the way to go.  Thats what I have done in the firefox version of fingerprint detection and it seems pretty good to me.

**Comment by gunesacar** [comment]
Thanks @cooperq, makes perfect sense to me, let me work on this.

But, one thing...
> Similarly I would but all of the checking whether this is a third party and whether privacy badger is enabled in the addon code. The content script can just send a domain name and the contents of local storage to the addon and let the addon do the heavy lifting.

I thought parsing local storage when PB is disabled or when the script is first-party may add an unnecessary overhead. But, of course, it may not be worse than the current overhead of making a call to [`webrequest.js`](https://github.com/EFForg/privacybadgerchrome/compare/master...gunesacar:super_cookie_detection?diff=unified&name=super_cookie_detection#diff-f70da41c29c6cfaaec74fcf92d1d465cR558) for `enabledAndThirdParty` check (which I modeled after [fingerprinting.js](https://github.com/EFForg/privacybadgerchrome/blob/ad74836bc05891fa32f9dda31e10db069f3c8135/src/fingerprinting.js#L258))

Let me know what you think and I'll go for it.

**Comment by cooperq** [comment]
hmm, we could do a check to see if privacy badger is enabled before we load the content script in the first place. Then in the content script we could check if we are the top frame like so: https://stackoverflow.com/questions/326069/how-to-identify-if-a-webpage-is-being-loaded-inside-an-iframe-or-directly-into-t#7769187

Assuming that if we are not the top frame that it is pretty likely that this frame is a third party. Of course we can then double check that on receipt of a message from the content script to be sure.

**Comment by gunesacar** [comment]
> we could do a check to see if privacy badger is enabled before we load the content script in the first place.

Cool, that's way better! As I understand, we can use [programmatic injection](https://developer.chrome.com/extensions/content_scripts#pi) for that . I'll give it a go.

**Comment by ghostwords** [comment]
I don't think programmatic injection currently supports before-anything-else-on-the-page injection ... See [crbug.com/478183](https://code.google.com/p/chromium/issues/detail?id=478183)

**Comment by gunesacar** [comment]
Thanks @ghostwords! For now, I left that part as it is, I'm scared about breaking the injection part.

@cooperq, I think I've implemented your suggestions about moving code from content script to addon and storing supercookie results in localStorage. I've also added some selenium tests.

Would be nice to have your comment on the current version:
https://github.com/EFForg/privacybadgerchrome/compare/master...gunesacar:super_cookie_detection

**Comment by gunesacar** [comment]
In addition to localStorage, we could store the supercookie state (found/not found) in `frameData` to get rid of expensive [localStorage lookups in heuristicBlocking](https://github.com/EFForg/privacybadgerchrome/compare/master...gunesacar:super_cookie_detection#diff-371a25d24420e6ab916c81f0c03d8f7cR440). See, https://jsperf.com/localstorage-vs-objects.

Does that make sense?

**Comment by cooperq** [comment]
I think storing supercookie state in memory is a good idea.  Looking over the code again it looks good, I'm looking forward to a pull request when you are ready!
