### ISSUE TITLE
detect fingerprinting and add to heuristic blocker

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#365]
This will probably get done by @ghostwords

**Comment by ghostwords** [comment]
WIP in https://github.com/EFForg/privacybadgerchrome/compare/master...canvas-fingerprinting.

**Comment by gunesacar** [comment]
I was going to add some selenium tests for canvas fingerprinting but cannot get it to work on this test page: https://jsfiddle.net/bL86p2tq/embedded/result/
Any ideas?

**Comment by ghostwords** [comment]
It's the old [no-sync-communication-with-injected-scripts issue] (https://github.com/EFForg/privacybadgerchrome/blob/8935682cb31be75f0c9b5d04d8ddd57297d950a1/src/fingerprinting.js#L257).

**Comment by ghostwords** [comment]
By the way, I'm getting `Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.` on that page from [here](https://github.com/EFForg/privacybadgerchrome/blob/8935682cb31be75f0c9b5d04d8ddd57297d950a1/src/supercookie.js#L56).

**Comment by gunesacar** [comment]
> It's the old no-sync-communication-with-injected-scripts issue.

Thanks, hope they fix 377978 soon, then.

> By the way, I'm getting Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document. in the console on that page from here.
 
It seems if the user has disabled 3rd party cookies and site data (@ghostwords can you confirm that you have this disabled?), we get a SecurityError when we try to access localStorage within the 3rd party frames we injected to.

Good thing is, the page scripts on 3rdP frames will already be blocked by the browser when they try to access localStorage, so I believe we won't miss anything due to this exception.

I'll handle the exception to prevent errors from polluting the console. Thanks for reporting it!

**Comment by ghostwords** [comment]
Confirmed, "Block third-party cookies and site data" is enabled on my Chromium.
