### ISSUE TITLE
Junk errors from missing tabs

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#410]
see this: http://paste.debian.net/195701/
was 'fixed' in #409 but we're still getting some errors, low priority but we should at least track it

**Comment by gunesacar** [comment]
Here's the relevant Chromium bug: [#451320](https://code.google.com/p/chromium/issues/detail?id=451320). Apparently, it's an issue with Chromium's Extension API.

**Comment by SwartzCr** [comment]
Interesting, and unfortunate
We can of course check thing by calling chrome.tabs.getAll and iterating through that, but this is obviously poor from a performance standpoint. For now I'd say we should just suck up the fact we're gonna have some junk errors (but less than before!)

**Comment by SwartzCr** [comment]
errors like this are still happening
Unchecked runtime.lastError while running browserAction.setBadgeText: No tab with id: 826.
    at updateCount (chrome-extension://hlhbomhbpchindedocliaflcfgkmobhj/src/background.js:760:26)

and I think they are causing the whole browser to lag, temporarily preventing the user from having control of their computer, reopening this so that we can investigate

**Comment by gunesacar** [comment]
I think these errors are due to tabs used for prerendering/prefetching. When I turn off prefetching ("Prefetch resources to load pages more quickly”) I stop getting the errors, which I commonly get when I search something on a new tab (likely to use prefetching). Also see, https://hg.adblockplus.org/adblockpluschrome/file/078e444afa92/chrome/ext/background.js#l195 (Chrome throws an error when you try to `get` a prerendering tab)

The PR adds a `bgTab` flag to prerendering tabs and won't call the setBadge functions until the tab becomes visible (with `onTabReplaced`). I avoided calling `chrome.tabs.get` too often (e.g. with every request.)

When you make a Google search and click the first link, you should see that the badge is updated almost immediately.

Let me know if you see any problem with this approach.

**Comment by SwartzCr** [comment]
Nice! I like the sound of this approach, I'll test it later today and merge if it seems to be working.

**Comment by SwartzCr** [comment]
solved in #438
