### ISSUE TITLE
Can no longer access CloudFlare-protected sites on Tor

### ISSUE THREAD

**Issue by Olathe** [EFForg/privacybadgerchrome#416]
This may be a tricky one.

When using Tor, CloudFlare-protected sites think that the large amount of traffic coming from a Tor exit node might be an attack, so they put up a CAPTCHA. Because Privacy Badger blocks google.com cookies during this phase of getting to the actual web page I want to see, CloudFlare's CAPTCHA says it can't connect to the CAPTCHA provider, and so I can't get to the website without turning off Privacy Badger or disabling the google.com cookie block.

Please unblock google.com cookies, but only when the page is a CloudFlare CAPTCHA page. This might best be done by looking at the HTML title tag, which is unique to CloudFlare CAPTCHA pages.

**Comment by Olathe** [comment]
I found that CloudFlare switches between various CAPTCHA providers and that this only affects one of them.

**Comment by cooperq** [comment]
Honestly, I strongly reccomend that you don't use privacy badger in conjunction with Tor. You should be using Tor Browser Bundle to browse with tor for a number of safety reasons, and you should not be modifying tor browser bundle since this can make you fingerprintable.

**Comment by cooperq** [comment]
I will try to make a fix for this though

**Comment by SwartzCr** [comment]
I don't think we should be adding google.com to the domain exception list for all users, especially considering that this will greylist all google subdomains for all users
I agree with cooper that you might have better luck just relying on tor's built in protections
since this seems like a very specific use case I'm going to close this, and suggest that you use Privacy Badger's manual override for this situation
feel free to re-open if you can point us to a more specific CAPTCHA url
