### ISSUE TITLE
Facebook (and maybe others?) doesn't seem to be blocked

### ISSUE THREAD

**Issue by adikamdar** [EFForg/privacybadgerchrome#440]
I opened up these five tabs, but Facebook doesn't seem to be blocked or yellowed:

https://fortune.com/2015/06/23/uber-privacy-epic-ftc/
![screenshot 2015-06-23 11 29 20](https://cloud.githubusercontent.com/assets/1112044/8314038/ad9eeea6-199b-11e5-9c5f-e985031e7998.png)

http://www.yelp.com/
![screenshot 2015-06-23 11 29 43](https://cloud.githubusercontent.com/assets/1112044/8314044/b9a17bd8-199b-11e5-9ace-159f27b4e950.png)

http://www.forbes.com/sites/allbusiness/2013/12/04/the-9-best-to-do-list-apps-for-2014/
![screenshot 2015-06-23 11 33 23](https://cloud.githubusercontent.com/assets/1112044/8314046/bdd3c756-199b-11e5-9755-6879f90444f9.png)

http://time.com/aziz-ansari-modern-romance/
![screenshot 2015-06-23 11 30 39](https://cloud.githubusercontent.com/assets/1112044/8314049/c2f27606-199b-11e5-9971-4022da2be732.png)

http://www.laweekly.com/music/i-performed-as-a-bug-at-electric-daisy-carnival-5721065
![screenshot 2015-06-23 11 30 50](https://cloud.githubusercontent.com/assets/1112044/8314055/cc03fbb6-199b-11e5-94c6-9aed527a62a7.png)

**Comment by SwartzCr** [comment]
chrome version 43.0.2357.124 (64-bit) mac
facebook was in localStorage seenThirdParties, but it didn't seem to be being updated

**Comment by cooperq** [comment]
turns out this was happnening because adi had third party cookieblocking turned on. Privacy badger had seen facebook trying to set a cookie once so it was in the seenThirdParties data structure (thus showing up in the popup) but it wasn't sending cookies after that so it wasn't being marked as tracking on any of the other sites. 

The solution for this is to change `hasCookieTracking()` in lib/heuristicblocking.js:452 to check for cookies in the cookie jar instead of in the headers

**Comment by cooperq** [comment]
an unrelated bug is that the options button is always highlighted in adis browser for some reason.

**Comment by cooperq** [comment]
This will be fixed by fixing #446

**Comment by cooperq** [comment]
fixed by #459
