### ISSUE TITLE
Privacy badger chrome warning

### ISSUE THREAD

**Issue by rnavaneethan** [EFForg/privacybadgerchrome#533]
![image](https://cloud.githubusercontent.com/assets/197331/9143297/172eb938-3d63-11e5-8397-9a4d9b37b105.png)

Chrome is throwing above warning after using privacy badger for some time.

**Comment by TheDudeWithAClue** [comment]
I had the same experience and uninstalled PB an hour after I installed it. Shame. I have few other extensions installed.

**Comment by terrorist96** [comment]
Yep.

**Comment by TheDudeWithAClue** [comment]
I have a relatively new machine running Win 8.1 with plenty of RAM and very few other applications running e.g. WinPatrol and Secunia PSI. I don't keep a large number of tabs open in Chrome.

I tried disabling all other extensions and leaving Privacy Badger running by itself but still received the notification that it was slowing Chrome down. Until this issue is resolved, Privacy Badger will remain uninstalled on my machine.

**Comment by Jelv** [comment]
I get the same message on my MacBook Air, but I dont notice the lag. I will keep the extension running and hope they fix there issues with Google (Chrome) soon.

**Comment by Jelv** [comment]
Duplicate from https://github.com/EFForg/privacybadgerchrome/issues/473

**Comment by rnavaneethan** [comment]
Closing as this is duplicate issue.

**Comment by TheDudeWithAClue** [comment]
Of course you'd close it rather than fix it.

**Comment by rnavaneethan** [comment]
@TheDudeWithAClue I'm just someone reported this issue just like you. I closed this in favor of the same issue reported earlier.

**Comment by Stexxen** [comment]
@TheDudeWithAClue chill, you joined yesterday, Can I suggest you read up how issues work in github.

**Comment by TheDudeWithAClue** [comment]
Nope. You chill, asshole.
