### ISSUE TITLE
PB don't block google-analytics.com !

### ISSUE THREAD

**Issue by hamidre2a** [EFForg/privacybadgerchrome#538]
google analytics track users but PB dont block it !

**Comment by cooperq** [comment]
This is because google analytics runs in the first party context not the third party, so privacy badger's heuristic doesn't see it as a tracker. See #340 for further info and #367

**Comment by MichaelTunnell** [comment]
This is good because technically Google Analytics tracks interaction with the specific website it is being ran on and thus PB should allow it.

Ideally someone would make an open source alternative to Google Analytics but that would be so freaking difficult I don't know if that will ever happen.

Anyway, I'm glad that PB doesn't block GA.

**Comment by dhowe** [comment]
Already exists: Piwik, open analytics platform 
https://piwik.org/

**Comment by MichaelTunnell** [comment]
@dhowe thanks, I did actually find Piwik previously but never thought to update this thread. Thanks for providing this solution in case people find this thread in the future.
