### ISSUE TITLE
Calls to localhost:3131 can't be whitelisted

### ISSUE THREAD

**Issue by carlo** [EFForg/privacybadgerchrome#542]
PB 2015.8.5.1, Chrome 44.0.2403.130, OS X.

I'm running [a dotjs server](https://github.com/defunkt/dotjs) on `localhost:3131`. The related dotjs Chrome extension is fetching a JS script from there for each page I am visiting.  Naturally, I want those whitelisted.

On any given page, PB will block the call to `localhost`.  I can seemingly whitelist the `localhost` domain using the settings overlay but when I reload the page (or visit any other page) `localhost` is blocked again.  The curious thing is that when I visit the PB Options screen, "User Filter Settings" tab, `localhost` is whitelisted there.

**Comment by SwartzCr** [comment]
so it sounds like there are two problems, one is that your user settings aren't showing up on specific pages but are showing up in the options page. Is this happening for any other domains?
This issue might have to do with the substring matching code in adblock where because a different localhost is getting a rule set for it it's overriding your rule for localhost:3131. If you don't notice this options page dispairity for any other site I'd recommend this:
go into chrome://extensions, turn on developer mode, and open up the background page for privacy badger (there should be a little link ithat says Inspect Views: Background Page, then go to the console in that popup)
Then edit the whitelist data structures manually. The call should be something like 
FilterStorage.addFilter(Filter.fromText('localhost:3131'), FilterStorage.knownSubscriptions.userGreen)
and then you can try to remove it from the frequency hueristic
find it with: FilterStorage.knownSubscriptions.frequencyHeuristic.filters
and then do
FilterStorage.removeFilter($filter, FilterStorage.knownSubscriptions.frequencyHueristic)

**Comment by carlo** [comment]
Thank you, @SwartzCr, your suggestion worked.
