### ISSUE TITLE
Tweet button gets replaced twice?!

### ISSUE THREAD

**Issue by KommX** [EFForg/privacybadgerchrome#553]
Example:
https://www.rhein-neckar-loewen.de/news/loewen-news/detail/5737

![twitter_replace](https://cloud.githubusercontent.com/assets/7859245/9246730/c5c603d6-41ad-11e5-9587-ee7b29a4c789.png)

**Comment by SwartzCr** [comment]
this is a race condition that @gunesacar was dealing with earilier wrt to google plus buttons, we never managed to come up with a perfect solution

**Comment by SwartzCr** [comment]
The real question here is what to do with social widget replacements.
They seem somewhat unmaintainable, and the original contributor (@froeschele) isn't around to keep them up to date. As some users have pointed out PB is replacing non-tracking widgets (https://github.com/EFForg/privacybadgerfirefox/issues/593)
It might be worth considering removing widget replacement until we can support it fully and just let normal PB blocking take care of them.

**Comment by cooperq** [comment]
I don't think we should remove widget replacement, it is one of our nicest features in my opinion, and often people aren't happy with the normal pb blocking since they actually like to use the widgets. 
The blocking of non tracking widgets is a non-issue IMO since we are going to get some false positives I would rather be on the safe side and block more widgets than we need to since it doesn't seem to actually create much of a usability problem. 

It seems to me that widget blocking is actually working pretty well. I think all we need to do is fix the race condition here that is creating two widgets.

**Comment by cooperq** [comment]
Okay, This should be completely fixed in the latest version of privacy badger. As of today I have only deployed it to 10% of users (it has some huge changes!) but if you want to try it out early you can take the following steps. 
1. Download the crx file [from the chrome web store] (https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1rX98iOE5SwxVXgdVTMTKqobiCFyOuS_jNFoVMdRhW-bEA7QhvVJw2hrKrZS8b8ThMYsv0t-wxxLr4D-Sm2ZC1AMZSmuW2zjq5MsW529CVI2Rtq2QO7xWEQg/pkehgijcmpdhfbdbbnkijodmdjhbjlgp_main.crx)
2. Open a new tab to [chrome://extensions](chrome://extensions)
3. Drag the downloaded file and drop it onto the extensions window. 
You should now have Privacy Badger version 2016.5.15
If this doesn't fix the problem please let me know. If you find any new bugs please file a separate issue.

**Comment by ghostwords** [comment]
I don't think this was fixed as part of the [May 2016 release](https://github.com/EFForg/privacybadger/compare/chrome-2016.4.13...chrome-2016.5.16) ...
