### ISSUE TITLE
"User Filter Settings" is unclearable

### ISSUE THREAD

**Issue by cilefen** [EFForg/privacybadgerchrome#589]
I can't seem to remove domains from "User Filter Settings", which is, ironically, very non-privacy respecting:

<img width="704" alt="screen shot 2015-08-27 at 10 34 43 am" src="https://cloud.githubusercontent.com/assets/1977311/9523312/5f97ec00-4ca7-11e5-9762-619148a34b74.png">

**Comment by cooperq** [comment]
Interesting, I guess we should make a way to clear individual domains out of this.

**Comment by cilefen** [comment]
I would say individual and "clear all".

**Comment by cooperq** [comment]
So the problem with clearing all is that you would essentially be completely resetting privacy badger. Since it works on a heuristic and keeps a record of what to block (the user filter settings) clearing all means privacy badger would block nothing. 

I think that this would be roughly akin to giving users a foot seeking gun.

**Comment by cilefen** [comment]
Ah, I see. Let's keep this to individual removals then. 

An extension reset option would be nice. And I am like "Adblock must have that, right?" Looks like no.

**Comment by SwartzCr** [comment]
if you want to reset privacy badger you can simply delete it from chrome and then re-install it. That should reset all the data structures. If you want to get rid of certain 3rd parties right now I can explain how to do that in the browser console if you'd like

**Comment by Tahirih-Natang** [comment]
@SwartzCr by getting rid of the 3rd parties in the browser console are you referring to the following procedure:
1. Right-click on the domain and select inspect element; so that console opens with element highlighted
2. Right-click on the highlighted element and select delete node

If its the case why not rather make provision for a drop or delete icon against each 3rd party so that the undesired ones can be gotten rid of?

**Comment by cooperq** [comment]
I believe what @SwartzCr was referring to is uninstalling privacy badger and reinstaling it. Unfortunately deleting an element from the dom is not enough to remove it from privacy badgers data store. It will simply come back the next time you load the popup or options page. To actually remove things you would have to remove them from the filter lists.
