### ISSUE TITLE
Social widget blocking

### ISSUE THREAD

**Issue by maps82** [EFForg/privacybadgerchrome#599]
Hi! I just migrated from ShareMeNot to Privacy Badger when I read that the former one stopped further development.

I see that PB replaces the Facebook share and like buttons, but looking in the chrome network inspector, there are still unblocked http requests that send the current URL to Facebook (see screenshot). That's also the case on the ShareMeNot Test Page (http://sharemenot.cs.washington.edu/Test%20Installation.shtml).

With ShareMeNot, those requests get completely blocked. So why is PB a replacement for ShareMeNot in it's default configuration when it doesn't block the requests?

<img width="1480" alt="socialnotblocking" src="https://cloud.githubusercontent.com/assets/12223156/9698622/9784b822-53bf-11e5-84fa-898f080f464a.png">

**Comment by cooperq** [comment]
Because privacy badger is heuristic based it has to learn over time what is tracking you before it can block anything. With that in mind, it's possible that privacy badger might not have learned to block facebook yet in your case. Browse around a little more and it should start blocking facebook, google, etc.
