### ISSUE TITLE
isPrivacyBadgerEnabled is writen poorly

### ISSUE THREAD

**Issue by SwartzCr** [EFForg/privacybadgerchrome#623]
Privacy Badger has the ability to turn itself off for certain sites. The list of these sites is stored in localStorage, meaning that they're a JSONified string.
For every page load Privacy Badger loads this string from localStorage, parses it as JSON and then iterates through all sites on that list to see if the current domain matches any of them.
This should be a smarter data structure that requires less load time (read from localStorage for each page load??) and easier search (maybe hash it on startup?)

**Comment by josmcg** [comment]
I'll take a look at it!

**Comment by sam5125** [comment]
A possible pruning can be achieved by adding one more layer of abstraction, in the JSON with reference to beginning alphabet of the given white-listed domain. In this way we need not to do an exhaustive search.

**Comment by Tahirih-Natang** [comment]
@sam5125 what if the white-list is growing? Firstly I will like to propose a binary search algorithm to start with. Such that on will not have to go through the entire list before the can know if the domain is blacklisted or not.

**Comment by sam5125** [comment]
@Tahirih-Natang  It can be even more meaningful if the list is growing as we will be able to abstract out the domains by name. Of course binary search is a great option. My opinion was to modify the data structure such that we can prune most of the results altogether. 
@SwartzCr It is just a suggestion but will that be of any use as far as optimization is concerned as it will highly depend on the amount of data(specifically domains) to be white-listed.

**Comment by SwartzCr** [comment]
I think the problem right now is that it loads it from and writes it to disk for every check. If it was stored in memory as an object it would have constant time look-up time, which would be faster than any search.
While improving the search algorithm might help a little, it doesn't help that we're still reading it all from disk for every call.
So what we need is a way to make sure that it's always current in memory and then the read time will be greatly improved.

**Comment by SwartzCr** [comment]
As far as how many domains will be in the whitelist, it will be relatively small, almost always under 100

**Comment by josmcg** [comment]
@SwartzCr I agree. When is the utils object instantiated and when is it killed? I'm not super familiar with chrome apps so I'm not sure how this cycle works. Do apps reload at every page? If not we should parse the array at startup, and cast them to String objects so our `===` won't have to do that every time.

**Comment by SwartzCr** [comment]
we have a background page object which runs all the time (you can look at it from the developer console) and see what it's data structures look like. I assume the start-up stuff would be in src/background.js but I haven't taken a look at it.

**Comment by nextLane** [comment]
@SwartzCr This essentially deals with the sites that are added to disabledSites variable in localStorage, yes? Presently, it is stored as list I guess we would be able to resolve if we save it as object i.e. hash type as is the supercookieDomains in image attached below. Would that suffice?
![selection_001](https://cloud.githubusercontent.com/assets/8895985/10664058/bb24a010-78dd-11e5-975e-697ee4569ec9.png)

**Comment by Kinnera323** [comment]
@nextLane You idea seems to be good. But if you store as supercookieDomain object whose key will be the domain and value needs to be Boolean, assuming we use the object same as superCookieDomain(Similar to python dictionaries where key -> domain, value -> boolean) and store the disabled sites, the values for all the domains should be true because disabledSites contains the list of sites where privacyBadger is disabled. It makes the search easier but  @SwartzCr primarily focuses on  storing the disbaledSites in memory rather than  localStorage where as the search optimisation is secondary

**Comment by nextLane** [comment]
@Kinnera323 Hi! I have some confusion here, can you please elaborate what you mean by "storing the disabledSites in memory", which memory essentially and why so?

**Comment by cooperq** [comment]
What @SwartzCr is trying to say (and which I agree with) is two things:

1. disabledSites should be initialized from localStorage and stored in memory when privacy badger starts. Whenever a user modifies userStorage it should first be modified in memory and then asynchronously written back to local storage. The reason for this is that IO operations from memroy are orders of magnitude faster than IO operations from the disk (which is what happens when you use local storage). 
2. The datastructure for disabledSites should be an object instead of an array, similar to what is in supercookieDomains with domains as keys and the value always boolean true. This way we can test if a domain is disabled with a simple call like `if(disabledSites[domain])` which is the fastest way to determine if a value is in a collection (https://jsperf.com/array-indexof-vs-object-key).

**Comment by nextLane** [comment]
@cooperq Some doubts regarding the first point, "Firefox starts out by reading all of the data from localStorage into memory for the page’s origin. " as this article says https://www.nczonline.net/blog/2012/04/25/the-performance-of-localstorage-revisited/  , wonder if this happens here too.
Second is covered in referenced commit. 
@all: Relevant read: https://hacks.mozilla.org/2012/03/there-is-no-simple-solution-for-local-storage/comment-page-1/

**Comment by cooperq** [comment]
Ah interesting! Though he does point out in that article that in memory objects are still faster than localStorage.

**Comment by cooperq** [comment]
Fixed! https://github.com/EFForg/privacybadgerchrome/wiki/Help-test-Privacy-Badger-for-chrome
