### ISSUE TITLE
yammer.com

### ISSUE THREAD

**Issue by melgoetz** [EFForg/privacybadgerchrome#647]
Yammer, after login with Privacy Badger enabled, shows the following message:

Tips for using Yammer with a screen reader (Office Help site) 
Skip to main content. 
Also, you can press '?' to show keyboard shortcuts. Also, you can press the question mark key to show keyboard shortcuts.

Some of those are non-working links. There is no way to get it to recognize that I'm not using a screen reader.

**Comment by sam5125** [comment]
Hello..
That does not seem to be a bug with privacy badger. Looking at the page source of yammer, it obtains its javascript files from https://c64.assets-yammer.com/ . When this tracker is disabled by privacy badger then it is unable to fetch the requisite assets required to render the webpage. And the links which you are seeing on the landing page are because they are statically written in a div container. To land onto main page just unblock the tracker c64.assets-yammer.com . It should work.

**Comment by cooperq** [comment]
@melgoetz can you tell me which domains are being blocked by privacy badger on  yammer.com?

**Comment by melgoetz** [comment]
@cooperq : @sam5125 is totally correct about this. Updating the tracker to only block cookies from c64.assets-yammer.com fixed the issue.
