### ISSUE TITLE
inconsistent blocking

### ISSUE THREAD

**Issue by zassmin** [EFForg/privacybadgerchrome#656]
Hi, 

Privacy Badger is blocking the iframe on womenwhocode.com/donate on my chrome browser. When other people downloaded Privacy Badger to test on chrome, it didn't block them from that iframe. Thoughts?

**Comment by cooperq** [comment]
This is because Privacy Badger uses a heuristic to decide what to block, instead of a black list. See this FAQ entry for more info: https://www.eff.org/privacybadger#ui-accordion-faqfield_field_questions_73969-header-2

For now you can simply drag the sliders for the iframed domain to green by clicking on the privacy badger icon, which should fix the problem for you.
