### ISSUE TITLE
Removing direct access to Local Storage throughout.

### ISSUE THREAD

**Issue by nextLane** [EFForg/privacybadgerchrome#685]
setItem and getItem are wrappers for accessing the Local Storage and generally recommended.
https://stackoverflow.com/questions/12632463/is-localstorage-getitemitem-better-than-localstorage-item-or-localstoragei/24904863#24904863

**Comment by cooperq** [comment]
According to the top answer on that question there are two differences:

1. a return of undefined vs null
2. access to built in properties of localStorage can be problematic

Otherwise both are supported and roughly comparable in speed I believe. I don't particularly have a preference for which style we use, but whichever we choose we should be consistent.

**Comment by cooperq** [comment]
Fixed! https://github.com/EFForg/privacybadgerchrome/wiki/Help-test-Privacy-Badger-for-chrome
