### ISSUE TITLE
Developer tools would be nice, why is PB blocking us?

### ISSUE THREAD

**Issue by falstro** [EFForg/privacybadgerchrome#694]
We're currently in the process of providing a third party plugin for web sites, and immediately PB blocked our `api...` host. I have no idea why, and it would be nice if there was some way to find out which part of the heuristic triggered, to see if we can somehow avoid it. We do not set any cookies or otherwise track users, regardless of DNT, so there's no obvious reason why it should block us.

I'm guessing we're getting blocked because we use persistent storage, but I don't know for sure.

**Comment by cooperq** [comment]
Privacy Badger does indeed use the html5 local storage api as a heuristic to decide what is a tracker, so if you are storing some information there that is probably the culprit. The best way to get yourself unblocked is to adopt EFF's Do Not Track policy document, which shouldn't be much of a problem since you say you are not tracking anyway! If you adpot the DNT policy privacy badger will no longer block your domain. You can find more information at https://eff.org/dnt-policy

**Comment by falstro** [comment]
I appreciate the response, and it is helpful in this particular case. I still think it would be useful with a 'developer tool' section of the plugin, though, showing why a site was blocked.

Thanks again.
