### ISSUE TITLE
PB issues warnings to web console when disabled for site.

### ISSUE THREAD

**Issue by jacob-lee** [EFForg/privacybadgerchrome#730]
PB does not appear to entirely respect site-specific settings. For example, disabling for site jsfiddle still gives this message in web console: 

10:48:55.554 Found hi-entropy localStorage:  812  bits "https://jsfiddle.net/" draft[241278254]1 jsfiddle.net:65:1

See this stack overflow for discussion of another user having similar issue back in August:

http://stackoverflow.com/questions/31953321/firefox-40-what-does-the-found-hi-entropy-localstorage-message-mean

**Comment by cooperq** [comment]
Thanks! Hopefully someone can look into this eventually

**Comment by gunesacar** [comment]
I guess this log comes from PB for **Firefox**.

In the Chrome extension, this log line is commented since June 2015:
https://github.com/EFForg/privacybadgerchrome/blame/master/src/utils.js#L333
Actually, I'm not sure whether it was uncommented at any time. I checked the latest release version (2015.12.3_0) and it's commented in there too.

The code that checks for the localStorage supercookies does not run when PB is disabled for the current site:
https://github.com/EFForg/privacybadgerchrome/blob/master/src/supercookie.js#L120-L122

Apparently it is PB for Firefox:
https://github.com/EFForg/privacybadgerfirefox/blob/438b079a03a60cc1edb81d1e3458231b7474c986/data/supercookie.js#L106

**Comment by gunesacar** [comment]
I believe this bug relates to PB for Firefox and can be closed. See https://github.com/EFForg/privacybadgerfirefox/pull/729
