### ISSUE TITLE
Privacy Badger reveals incognito brwosing activity

### ISSUE THREAD

**Issue by mrphs** [EFForg/privacybadgerchrome#829]
If incognito mode has one good use, it's that it doesn't keep history or cookies of the session. However, if you've privacy badger enabled for incognito, you can go to setting page and see all the domains visited (including those in incognito mode). I tested this on a fresh 'Chrome Persona'. Here are the steps I took:

1. Installed PB
2. Allowed in incognito from chrome extensions settings
3. Browsed to a site in incognito mode
4. Quit chrome
5. Re-opened chrome, went to PB settings
6. The website I visited and all of its related domains appear.

It should probably:
- Forget what happens in incognito mode as soon as the session is ended
- And maybe hide the list of ALL accessed/loaded/blocked domains?

**Comment by rcutmore** [comment]
There are changes in the works that should fix this issue.

**Comment by cooperq** [comment]
Thanks for checking this out @mrphs! Okay, This should be completely fixed in the latest version of privacy badger. As of today I have only deployed it to 10% of users (it has some huge changes!) but if you want to try it out early you can take the following steps. 
1. Download the crx file [from the chrome web store] (https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1rX98iOE5SwxVXgdVTMTKqobiCFyOuS_jNFoVMdRhW-bEA7QhvVJw2hrKrZS8b8ThMYsv0t-wxxLr4D-Sm2ZC1AMZSmuW2zjq5MsW529CVI2Rtq2QO7xWEQg/pkehgijcmpdhfbdbbnkijodmdjhbjlgp_main.crx)
2. Open a new tab to [chrome://extensions](chrome://extensions)
3. Drag the downloaded file and drop it onto the extensions window. 
You should now have Privacy Badger version 2016.5.15
If this doesn't fix the problem please let me know. If you find any new bugs please file a separate issue.

**Comment by cowlicks** [comment]
Should this be closed since it is fixed in the latest release?

**Comment by cooperq** [comment]
indeed it is!
