### ISSUE TITLE
firstRun.html keeps running

### ISSUE THREAD

**Issue by justforgroups** [EFForg/privacybadgerchrome#834]
Hi,
After clearing cookies etc. from PC, next time I reopen Chrome, the "thanks for installing me" screen from privacy badger opens in a new window: chrome-extension://<code>/skin[/firstRun.html](http://i.imgur.com/m6T4pta.png)

It's extremely annoying. It's obviously checking a cookie or something, and since I'm clearing them, believes it's a brand new installation and displays that html file.

Could this be stopped please? You can put that information under the Options link of the extension tab if you want, and people will go to it if they're interested.

Thks.

**Comment by cooperq** [comment]
Okay, This should be completely fixed in the latest version of privacy badger. As of today I have only deployed it to 10% of users (it has some huge changes!) but if you want to try it out early you can take the following steps. 
1. Download the crx file [from the chrome web store] (https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1rX98iOE5SwxVXgdVTMTKqobiCFyOuS_jNFoVMdRhW-bEA7QhvVJw2hrKrZS8b8ThMYsv0t-wxxLr4D-Sm2ZC1AMZSmuW2zjq5MsW529CVI2Rtq2QO7xWEQg/pkehgijcmpdhfbdbbnkijodmdjhbjlgp_main.crx)
2. Open a new tab to [chrome://extensions](chrome://extensions)
3. Drag the downloaded file and drop it onto the extensions window. 
You should now have Privacy Badger version 2016.5.15
If this doesn't fix the problem please let me know. If you find any new bugs please file a separate issue.

**Comment by justforgroups** [comment]
Hi cooperq,
I can confirm Privacy Badger version 2016.5.15 fixes the issue!
To recap, I installed Privacy Badger version 2016.5.15; Performed a full run of CCleaner (including Internet Cache), closed Chrome, opened it up, and the PB file did not open.

Thanks for that!
