### ISSUE TITLE
Printouts via console.log()

### ISSUE THREAD

**Issue by alexristich** [EFForg/privacybadgerchrome#879]
I'm looking to investigate a couple of bugs, but for the life of me can't figure out how to print to the console.

In searching the code, I found `pb.DEBUG`, which I set to true, but after reloading the unpacked extension it doesn't seem to be working. It's my first time modifying chrome extensions, so I wasn't sure if I was loading the extension properly. To test this, I modified the version to "2016.7.11" and reloaded it. This worked, so I know I'm loading the extension properly, but I'm now somewhat lost on what steps to take to enable console printouts via the standard Chrome console (or whether I ought to be looking elsewhere?).

Thanks!

**Comment by cowlicks** [comment]
Hi @alexristich, you should inspect the background page of the extension, then in that console set `pb.DEBUG = 1`. Debug messages will appear in this console. Do not reload the extension after doing this as it resets `pb.DEBUG = 0`.

We have a `pb.log` method which checks if `DEBUG == 1` to print messages. But there are some places we are still using `console.log` for debug statements, particularly in the popup. This should be fixed in the next release.

Also note that the "popup" runs in a different process/context, so `console.log` statements in the popup's code won't appear in the background console, but `pb.log` statements should.

You can get a console to inspect the  popup's context by right clicking it and selecting "Inspect popup".

Here is a nice overview of web extensions: https://developer.chrome.com/extensions/overview

**Comment by alexristich** [comment]
@cowlicks Most excellent, thank you kindly! It would have taken me ages to figure this out. So many logging statements... an absolute pleasure when poking around in a new project! Also, I've never thought to click on about "inspect popup" - very useful! 

Thanks for the link to the overview - that will undoubtedly come in handy while delving deeper into the code. I'll post if I have any other questions, but for now I'm going to revel in these glorious console logs. :)
