### ISSUE TITLE
Question: Where do "Report Broken Site" reports go?

### ISSUE THREAD

**Issue by cowlicks** [EFForg/privacybadgerchrome#884]
When someone reports a broken site with privacy badger, how does the EFF handle these?

It seems like most fixes for broken sites happen in issues and pull requests on github. But given the nature of the problem, it would probably be more efficient to have these fixes happen through another channel. Which is what I'd assume the "Report Broken Site" button does, but I can't find any information about how these reports are handles.

**Comment by cooperq** [comment]
Basically they go into an anonymized database and then I look at the 10 or so sites which are reported broken the most that week and try to fix them. Doesn't always happen as quickly as that, but that's the idea. It's to get a sense of broad trends in broken sites rather than as a bug reporting mechanism.
