### ISSUE TITLE
Tests fail intermittently on travis

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#924]
Tests fail about half the time on travis, no idea why. @gunesacar you are the master of selenium tests, any thoughts?

**Comment by gunesacar** [comment]
It turned out the test failures were due to several different issues:

* A chromedriver bug related to GLib, DBus and Xvfb, causing a browser hang during the initialization, e.g.: https://travis-ci.org/EFForg/privacybadgerchrome/builds/160205176#L540. Fixed thanks to:
https://github.com/SeleniumHQ/docker-selenium/issues/87#issuecomment-187580115

* Trying to interact with an alert box before making sure it is really present or not. Now we wait for the alert to be present before we continue.

* `test_should_detect_ls_of_third_party_frame` still fails intermittently (ballpark, 5% of the time).
  This is the only test that *rightfully fails*, possibly due to https://github.com/ghostwords/chameleon/issues/5. AFAIR @ghostwords knew more about this issue.

For such intermittent failures, we started using `travis_retry`, Travis will rerun the tests when there's a failure.

Failures became very uncommon after these fixes. I ran the tests 20 times to trigger intermittent fails:
* https://travis-ci.org/gunesacar/privacybadgerchrome/builds/160220999: No single failure.
* https://travis-ci.org/gunesacar/privacybadgerchrome/builds/160214453: Only 2 of the 280 tests have failed (`test_should_detect_ls_of_third_party_frame`, so it's expected).

Please check my pull request and let me know if anything is unclear.

**Comment by cooperq** [comment]
This is excellent work! Thanks @gunesacar, this will make my life much easier :smile_cat:

**Comment by gunesacar** [comment]
You're welcome. Feel free to ping me if they start to fail again.
