### ISSUE TITLE
Simplify incognito handling

### ISSUE THREAD

**Issue by cooperq** [EFForg/privacybadgerchrome#932]
No two badgers!

**Comment by ghostwords** [comment]
Might be simpler to check for [tab.incognito](https://developer.chrome.com/extensions/tabs#property-Tab-incognito) whenever doing anything sensitive that shouldn't take place in Incognito tabs, such as persisting data. Not 100% sure, but an idea for investigation. This came up when I noticed DNT policies and cookieblock list resources get fetched twice on startup and went to see what that's about.

**Comment by cowlicks** [comment]
@ghostwords @cooperq  feel free to hmu to chat about the current implementation.

IIRC besides persisting data, the problem was that a badger has some in-memory tab data structure which holds info about the tabs it has seen. This gets persisted to disk asynchronously as needed. The problem with having one badger was that all tabs, both incognito and not, would share this datastructure. Which would expose information from the incognito session in the normal session.

One partial solution would be to only create the incognito badger only when the incognito browser session is started.

**Comment by cooperq** [comment]
@cowlicks would you be down to walk us through the current architecture and help brainstorm about this?

**Comment by cowlicks** [comment]
@cooperq sure, just text me.

**Comment by ghostwords** [comment]
This is happening in #951.
