### ISSUE TITLE
need to train more for privacy badger a/c to concept of PB

### ISSUE THREAD

**Issue by ghajini** [EFForg/privacybadgerchrome#960]
@cooperq 
it need to train more for privacy badger to compete with ublock origin
e.g in this site
 http://www.songspk.kim/indian_movie/Mirzya-2016.html
in order to block trackers, privacy badgers need time to understand trackers heuristically also i get phishing sites redirects such as liveadexchanger, terraclicks and other malware sites......ublock just do on its way......
so heuristic way is just time consuming.
e.g 
1. go here http://www.songspk.kim/indian_movie/Mirzya-2016.html

2. click on "play songs" 

3. instead of playing songs it just gets series of popups of phishing sites and do not play the songs.......

4. in order to listen the song i have to move slider to red of unknown trackers in dashboard of PB which were not blocked default by PB

**Comment by alexristich** [comment]
Thanks for your comments! Privacy Badger and uBlock Origin should work fairly well in unison, so I'd recommend using them both if you're visiting sites that contain a lot of phishing and redirects.

As @cooperq mentioned in #886, Privacy Badger only blocks domains once it has detected them tracking you across multiple sites. It uses a different model than uBlock, so it will dynamically detect trackers rather than use an existing list of domains that are determined to be trackers.

The value of heuristic detection is that it can better block newer trackers that might not yet have made their way into the manually assembled list used by uBlock, etc. On the heuristic itself, I'm hoping to work with another collaborator on this to try to improve the detection rate.

The heuristic approach does require more page visits to classify something as a tracker, though it should be noted that the primary privacy concern with tracking is not which pages you visit on a specific domain (since the site itself can track that and tell others about it), but the fact that trackers can see you across multiple websites, thus getting a glimpse into your browsing history and being able to build a profile of you.

I'll close this issue for now, as we are planning on improving the heuristic and the phishing, etc. is outside of the scope of what Privacy Badger aims to offer, and can be better defended against by using both Privacy Badger and uBlock Origin.

**Comment by ghajini** [comment]
I see some "allowed things" in PB are blocked in ublock origin....so whether thing is blocking /allowing when using PB+Ublock origin

**Comment by alexristich** [comment]
I'm not 100% sure, but I think that if uBlock catches it and Privacy Badger doesn't, you're still good to go.

**Comment by cooperq** [comment]
if ublock blocks something privacy badger will not unblock it.
