### ISSUE TITLE
Privacy badger causing chromium to lockup when using multiple tabs

### ISSUE THREAD

**Issue by calexil** [EFForg/privacybadgerchrome#983]
as the title states, it appears that privacy badger is causing a serious memory leak in chromium which causes the browser to be completely dumped from memory for about 30 seconds. 

I think the extension is trying to run on EVERY open tab.... not just the active one....which seems silly

Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 18 (64-bit)

Privacy Badger 2016.9.7

**Comment by alexristich** [comment]
Hmm, that's strange. It does have a different "sub-instance" for each tab, namely the badge count and which trackers are blocked, but it shares the same instance across the whole session.

Is this happening frequently? If so, I'd be curious to know what Chrome's Task Manager is showing for memory and CPU usage during these times to see if either of these spike.

**Comment by calexil** [comment]
when it happens chrome task mgr says no tab is using any memory(they all say 0), it seems to be triggered by certain sites worse than others, for instance the paypal.com/vt virtual terminal seems to lock it up consistently, but other sites cause it as well.

regular taskmanager (mate-system-monitor) shows chromium using 2/3rds of my three cores and so does chromium taskmanager

unfortunately I cant really trace the issue since the logs dont really say anything, and I'm not too good with gdb, but I do know it's most likely PB because killing the extension and removing it fixed the problem, and when I tried initially tried to uninstall it the whole browser crashed.

**Comment by alexristich** [comment]
Thanks for the additional info. I'm surprised Chrome crashed when uninstalling an extension - even if the extension is problematic, it lives in a sandbox and basically gets all its permissions from Chrome's API. 

I'm not immediately sure what would be causing this, though @cooperq might have some further insight. One thing you can try is navigating to one of these problem pages and clicking the "Did Privacy Badger break this site? Let us know!" button in Privacy Badger.

Also, while it's a bit more work, you could try cloning from this repo to your local machine then installing the extension manually by going to `chrome://extensions`, clicking "Load unpacked extension..." then selecting the directory where you cloned the repo to. Some changes have been made since the 2016.9.7 version relating to Privacy Badger's operation across regular and incognito tabs, so I wonder if this may have helped with the issue.

**Comment by alexristich** [comment]
I talked with @cooperq about this briefly, and he agreed that it sounds like it would have been something external to Privacy Badger, as it seemed suspicious that the browser crashed when trying to uninstall an extension.

I'll close this issue for now, though if you do notice this occurring again and it looks to be related to Privacy Badger, please feel free to post here and I'd be happy to give it another look!

**Comment by calexil** [comment]
@alexristich Ill look into it further, thanks for the input
